"""create initial schema

Revision ID: b10787dd0d5f
Revises: 
Create Date: 2026-04-07 17:10:49.665079
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b10787dd0d5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
    op.create_table('borrowers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('external_id_number', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_borrowers_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_borrowers_full_name', 'borrowers', ['full_name'], unique=False)
    op.create_index('idx_borrowers_phone_number', 'borrowers', ['phone_number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'staff')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('before_state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('repayment_frequency', sa.Text(), nullable=False),
    sa.Column('periodic_interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('term_length', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('grace_period_days', sa.Integer(), server_default=sa.text('7'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("repayment_frequency IN ('weekly', 'monthly')", name='ck_loans_repayment_frequency'),
    sa.CheckConstraint("status IN ('draft', 'active', 'closed', 'overdue', 'defaulted', 'restructured', 'cancelled')", name='ck_loans_status'),
    sa.CheckConstraint('end_date >= start_date', name='ck_loans_end_date_after_start_date'),
    sa.CheckConstraint('grace_period_days >= 0', name='ck_loans_grace_period_days_nonnegative'),
    sa.CheckConstraint('periodic_interest_rate >= 0', name='ck_loans_periodic_interest_rate_nonnegative'),
    sa.CheckConstraint('principal_amount > 0', name='ck_loans_principal_amount_positive'),
    sa.CheckConstraint('term_length > 0', name='ck_loans_term_length_positive'),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_loans_borrower_id', 'loans', ['borrower_id'], unique=False)
    op.create_index('idx_loans_end_date', 'loans', ['end_date'], unique=False)
    op.create_index('idx_loans_start_date', 'loans', ['start_date'], unique=False)
    op.create_index('idx_loans_status', 'loans', ['status'], unique=False)
    op.create_index('uq_loans_one_active_per_borrower', 'loans', ['borrower_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=False),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payment_method', sa.Text(), nullable=True),
    sa.Column('reference_code', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_backdated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('recorded', 'voided', 'reversed')", name='ck_payments_status'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_borrower_id', 'payments', ['borrower_id'], unique=False)
    op.create_index('idx_payments_loan_id', 'payments', ['loan_id'], unique=False)
    op.create_index('idx_payments_payment_date', 'payments', ['payment_date'], unique=False)
    op.create_index('idx_payments_reference_code', 'payments', ['reference_code'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_table('repayment_schedule_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('principal_paid', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_paid', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('waived_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'partially_paid', 'paid', 'overdue', 'waived')", name='ck_schedule_items_status'),
    sa.CheckConstraint('installment_number > 0', name='ck_schedule_items_installment_number_positive'),
    sa.CheckConstraint('interest_due >= 0', name='ck_schedule_items_interest_due_nonnegative'),
    sa.CheckConstraint('interest_paid >= 0', name='ck_schedule_items_interest_paid_nonnegative'),
    sa.CheckConstraint('principal_due >= 0', name='ck_schedule_items_principal_due_nonnegative'),
    sa.CheckConstraint('principal_paid >= 0', name='ck_schedule_items_principal_paid_nonnegative'),
    sa.CheckConstraint('waived_amount >= 0', name='ck_schedule_items_waived_amount_nonnegative'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'installment_number', name='uq_schedule_items_loan_installment')
    )
    op.create_index('idx_schedule_items_due_date', 'repayment_schedule_items', ['due_date'], unique=False)
    op.create_index('idx_schedule_items_loan_id', 'repayment_schedule_items', ['loan_id'], unique=False)
    op.create_index('idx_schedule_items_status', 'repayment_schedule_items', ['status'], unique=False)
    op.create_table('late_charges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('schedule_item_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('trigger_date', sa.Date(), nullable=False),
    sa.Column('base_unpaid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('charge_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('charge_principal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('accrued_interest_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('principal_paid', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('interest_paid', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('waived_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('outstanding', 'partially_paid', 'paid', 'waived', 'voided')", name='ck_late_charges_status'),
    sa.CheckConstraint('accrued_interest_amount >= 0', name='ck_late_charges_accrued_interest_amount_nonnegative'),
    sa.CheckConstraint('base_unpaid_amount >= 0', name='ck_late_charges_base_unpaid_amount_nonnegative'),
    sa.CheckConstraint('charge_principal_amount >= 0', name='ck_late_charges_charge_principal_amount_nonnegative'),
    sa.CheckConstraint('charge_rate >= 0', name='ck_late_charges_charge_rate_nonnegative'),
    sa.CheckConstraint('interest_paid >= 0', name='ck_late_charges_interest_paid_nonnegative'),
    sa.CheckConstraint('principal_paid >= 0', name='ck_late_charges_principal_paid_nonnegative'),
    sa.CheckConstraint('waived_amount >= 0', name='ck_late_charges_waived_amount_nonnegative'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_item_id'], ['repayment_schedule_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_item_id', name='uq_late_charges_schedule_item_id')
    )
    op.create_index('idx_late_charges_loan_id', 'late_charges', ['loan_id'], unique=False)
    op.create_index('idx_late_charges_status', 'late_charges', ['status'], unique=False)
    op.create_index('idx_late_charges_trigger_date', 'late_charges', ['trigger_date'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('schedule_item_id', sa.UUID(), nullable=True),
    sa.Column('late_charge_id', sa.UUID(), nullable=True),
    sa.Column('allocation_type', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            allocation_type IN (\n                'late_charge_interest',\n                'late_charge_principal',\n                'regular_interest',\n                'regular_principal'\n            )\n            ", name='ck_payment_allocations_allocation_type'),
    sa.CheckConstraint('\n            (schedule_item_id IS NOT NULL AND late_charge_id IS NULL)\n            OR\n            (schedule_item_id IS NULL AND late_charge_id IS NOT NULL)\n            ', name='ck_payment_allocations_exactly_one_target'),
    sa.CheckConstraint('amount > 0', name='ck_payment_allocations_amount_positive'),
    sa.ForeignKeyConstraint(['late_charge_id'], ['late_charges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_item_id'], ['repayment_schedule_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_allocations_late_charge_id', 'payment_allocations', ['late_charge_id'], unique=False)
    op.create_index('idx_payment_allocations_loan_id', 'payment_allocations', ['loan_id'], unique=False)
    op.create_index('idx_payment_allocations_payment_id', 'payment_allocations', ['payment_id'], unique=False)
    op.create_index('idx_payment_allocations_schedule_item_id', 'payment_allocations', ['schedule_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payment_allocations_schedule_item_id', table_name='payment_allocations')
    op.drop_index('idx_payment_allocations_payment_id', table_name='payment_allocations')
    op.drop_index('idx_payment_allocations_loan_id', table_name='payment_allocations')
    op.drop_index('idx_payment_allocations_late_charge_id', table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index('idx_late_charges_trigger_date', table_name='late_charges')
    op.drop_index('idx_late_charges_status', table_name='late_charges')
    op.drop_index('idx_late_charges_loan_id', table_name='late_charges')
    op.drop_table('late_charges')
    op.drop_index('idx_schedule_items_status', table_name='repayment_schedule_items')
    op.drop_index('idx_schedule_items_loan_id', table_name='repayment_schedule_items')
    op.drop_index('idx_schedule_items_due_date', table_name='repayment_schedule_items')
    op.drop_table('repayment_schedule_items')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_reference_code', table_name='payments')
    op.drop_index('idx_payments_payment_date', table_name='payments')
    op.drop_index('idx_payments_loan_id', table_name='payments')
    op.drop_index('idx_payments_borrower_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('uq_loans_one_active_per_borrower', table_name='loans', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('idx_loans_status', table_name='loans')
    op.drop_index('idx_loans_start_date', table_name='loans')
    op.drop_index('idx_loans_end_date', table_name='loans')
    op.drop_index('idx_loans_borrower_id', table_name='loans')
    op.drop_table('loans')
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_index('idx_borrowers_phone_number', table_name='borrowers')
    op.drop_index('idx_borrowers_full_name', table_name='borrowers')
    op.drop_table('borrowers')
    # ### end Alembic commands ###
